extends Node
## Autoload "AudioManager": sound effects, music, volume/mute settings and lifecycle pausing.
##
## Buses "Music" and "SFX" are created at startup and routed to Master. All sounds are
## small WAV files in res://assets/audio (generated by tools/generate_audio.py); a missing
## file simply plays nothing, it never breaks the game.

const AUDIO_DIR: String = "res://assets/audio/"
const BUS_MUSIC: String = "Music"
const BUS_SFX: String = "SFX"
const SFX_POOL_SIZE: int = 12
const SFX_NAMES: Array = [
	"jump", "land", "wall", "combo_step", "combo_end_1", "combo_end_2", "combo_end_3",
	"speed_up", "ui_click", "ui_back", "game_over", "record", "danger", "unlock",
]
## Headroom for the music bus (dB).
const MUSIC_BASE_DB: float = -4.0

var _sfx_players: Array = []
var _sfx_next: int = 0
var _music_players: Array = []
var _active_music: int = 0
var _current_music: String = ""
var _streams: Dictionary = {}
var _app_paused: bool = false
var _music_paused: bool = false
var _fade_tween: Tween = null


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_ensure_buses()
	for i in range(SFX_POOL_SIZE):
		var p: AudioStreamPlayer = AudioStreamPlayer.new()
		p.bus = BUS_SFX
		add_child(p)
		_sfx_players.append(p)
	for i in range(2):
		var m: AudioStreamPlayer = AudioStreamPlayer.new()
		m.bus = BUS_MUSIC
		m.volume_db = -80.0
		add_child(m)
		_music_players.append(m)
	for n in SFX_NAMES:
		_get_stream(String(n))
	Events.settings_changed.connect(_on_settings_changed)
	apply_volumes()


func _ensure_buses() -> void:
	for bus_name in [BUS_MUSIC, BUS_SFX]:
		if AudioServer.get_bus_index(bus_name) == -1:
			AudioServer.add_bus()
			var idx: int = AudioServer.bus_count - 1
			AudioServer.set_bus_name(idx, bus_name)
			AudioServer.set_bus_send(idx, "Master")


func _on_settings_changed(key: String) -> void:
	if key == "*" or key.begins_with("vol_") or key == "mute":
		apply_volumes()


static func _to_db(linear: float) -> float:
	if linear <= 0.001:
		return -80.0
	return linear_to_db(linear)


## Applies master / music / effects volume and the mute switch from the settings.
func apply_volumes() -> void:
	AudioServer.set_bus_volume_db(0, _to_db(SettingsManager.get_float("vol_master")))
	AudioServer.set_bus_mute(0, SettingsManager.get_bool("mute"))
	var mi: int = AudioServer.get_bus_index(BUS_MUSIC)
	var si: int = AudioServer.get_bus_index(BUS_SFX)
	if mi >= 0:
		AudioServer.set_bus_volume_db(mi, _to_db(SettingsManager.get_float("vol_music")) + MUSIC_BASE_DB)
	if si >= 0:
		AudioServer.set_bus_volume_db(si, _to_db(SettingsManager.get_float("vol_sfx")))


# ---------------------------------------------------------------------------
# Streams
# ---------------------------------------------------------------------------
func _get_stream(sound_name: String) -> AudioStream:
	if _streams.has(sound_name):
		return _streams[sound_name]
	var path: String = AUDIO_DIR + sound_name + ".wav"
	var s: AudioStream = null
	if ResourceLoader.exists(path):
		s = load(path) as AudioStream
	_streams[sound_name] = s
	return s


func _make_loop(s: AudioStream) -> void:
	if s is AudioStreamWAV:
		var w: AudioStreamWAV = s
		if w.loop_mode == AudioStreamWAV.LOOP_DISABLED:
			w.loop_mode = AudioStreamWAV.LOOP_FORWARD
			w.loop_begin = 0
			w.loop_end = int(w.get_length() * float(w.mix_rate))


# ---------------------------------------------------------------------------
# Sound effects
# ---------------------------------------------------------------------------
func play_sfx(sound_name: String, pitch: float = 1.0, volume_db: float = 0.0) -> void:
	if _app_paused:
		return
	var s: AudioStream = _get_stream(sound_name)
	if s == null:
		return
	var p: AudioStreamPlayer = null
	for i in range(SFX_POOL_SIZE):
		var cand: AudioStreamPlayer = _sfx_players[(_sfx_next + i) % SFX_POOL_SIZE]
		if not cand.playing:
			p = cand
			_sfx_next = (_sfx_next + i + 1) % SFX_POOL_SIZE
			break
	if p == null:
		p = _sfx_players[_sfx_next]
		_sfx_next = (_sfx_next + 1) % SFX_POOL_SIZE
	p.stream = s
	p.pitch_scale = clampf(pitch, 0.25, 4.0)
	p.volume_db = volume_db
	p.play()


func play_click() -> void:
	play_sfx("ui_click", 1.0, -3.0)


func play_back() -> void:
	play_sfx("ui_back", 1.0, -3.0)


## Jump sound: higher and louder for faster (higher) jumps.
func play_jump(speed_ratio: float) -> void:
	play_sfx("jump", 0.92 + 0.38 * clampf(speed_ratio, 0.0, 1.0), lerpf(-6.0, 0.0, clampf(speed_ratio, 0.0, 1.0)))


func play_land(impact_speed: float) -> void:
	var k: float = clampf(absf(impact_speed) / 1400.0, 0.0, 1.0)
	play_sfx("land", 1.05 - 0.2 * k, lerpf(-14.0, -1.0, k))


func play_wall(speed_ratio: float) -> void:
	var k: float = clampf(speed_ratio, 0.0, 1.0)
	play_sfx("wall", 0.9 + 0.3 * k, lerpf(-9.0, 0.0, k))


## Rising "combo step" ping: one semitone higher per jump of the chain (max one octave).
func play_combo_step(jumps: int) -> void:
	var semitones: float = float(clampi(jumps - 1, 0, 12))
	play_sfx("combo_step", pow(2.0, semitones / 12.0), -2.0)


## Combo completion fanfare, tier 1 (small) .. 3 (huge).
func play_combo_end(tier: int) -> void:
	play_sfx("combo_end_%d" % clampi(tier, 1, 3), 1.0, 0.0)


# ---------------------------------------------------------------------------
# Music
# ---------------------------------------------------------------------------
func play_music(track: String, fade_seconds: float = 0.6) -> void:
	if track == _current_music:
		return
	var s: AudioStream = _get_stream(track)
	if _fade_tween != null and _fade_tween.is_valid():
		_fade_tween.kill()
	var old_player: AudioStreamPlayer = _music_players[_active_music]
	_active_music = 1 - _active_music
	var new_player: AudioStreamPlayer = _music_players[_active_music]
	_current_music = track
	_fade_tween = create_tween()
	_fade_tween.set_parallel(true)
	if old_player.playing:
		_fade_tween.tween_property(old_player, "volume_db", -60.0, fade_seconds)
		_fade_tween.chain().tween_callback(old_player.stop)
	if s != null:
		_make_loop(s)
		new_player.stream = s
		new_player.volume_db = -60.0
		new_player.stream_paused = _app_paused or _music_paused
		new_player.play()
		_fade_tween.tween_property(new_player, "volume_db", 0.0, fade_seconds)


func stop_music(fade_seconds: float = 0.5) -> void:
	_current_music = ""
	if _fade_tween != null and _fade_tween.is_valid():
		_fade_tween.kill()
	_fade_tween = create_tween()
	_fade_tween.set_parallel(true)
	for m in _music_players:
		var p: AudioStreamPlayer = m
		if p.playing:
			_fade_tween.tween_property(p, "volume_db", -60.0, fade_seconds)
	_fade_tween.chain().tween_callback(_stop_all_music)


func _stop_all_music() -> void:
	for m in _music_players:
		(m as AudioStreamPlayer).stop()


func current_music() -> String:
	return _current_music


## Pauses/resumes music only (the pause menu).
func set_music_paused(paused: bool) -> void:
	_music_paused = paused
	_apply_pause_state()


## Pauses/resumes ALL audio (app lost focus / returned).
func set_paused(paused: bool) -> void:
	_app_paused = paused
	_apply_pause_state()


func _apply_pause_state() -> void:
	for m in _music_players:
		(m as AudioStreamPlayer).stream_paused = _app_paused or _music_paused
	for s in _sfx_players:
		(s as AudioStreamPlayer).stream_paused = _app_paused
